lsコマンドを作るオブジェクト指向版の提出物
alto-I/ruby-practices pull request #3
Opened 2021-02-02 13:04 UTC by alto-I

2021-02-03 11:54 UTC, alto-I commented
よろしくお願いします！

2021-02-08 11:44 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +require_relative './ls_long'
自信がないのですが気になったので。`require_relative` でこのファイルと同じ階層から読むなら、`./` は冗長(relativeであることから自明)だと個人的には思うのですが、どこかでそういう書き方が推奨されていたとかですかね…。

2021-02-08 11:44 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +require_relative './ls_short'
同上。

2021-02-08 11:46 UTC, kakutani commented on 08.ls_object/ls_oop.rb
> +require './lib/ls'
ここは `require_relative` のほうがよさそう(パスの扱いは既にしたコメントを参考にしてみてください)

2021-02-08 11:49 UTC, kakutani commented
まずは、字面をざっと見ただけでコメントしちゃって恐縮です。

読んだ第一印象は、変数やメソッドなどの名前が丁寧に命名されていて、読み手への配慮が感じられて好印象です!(えらそう)

ちょっと時間が空いてしまうかもしれませんが、読み込んだらまたコメントします!

2021-02-09 00:38 UTC, kakutani reviewed
シンプルに書こうとしてる姿勢が伝わってきました!
オプションに応じて呼び出すところまで読みましたので、一旦コメントを残します。

コメント部分に限らず、ご自身で気づいた点などあれば修正していただいて構いません!

2021-02-09 00:38 UTC, kakutani commented on 08.ls_object/ls_oop.rb
> +path = ARGV[0] || '.'
`path`のデフォルト値がカレントディレクトリであるという知識は、呼び出す側よりも`Ls`オブジェクトが知っているほうがよさそうです。

2021-02-09 00:38 UTC, kakutani commented on 08.ls_object/ls_oop.rb
> +pathname = Pathname(path)
`Pathname`を使ってファイルパスをハンドルするという知識が`Ls`クラスから漏れていますね。
`Ls`クラスのクライントコード(`ls_oop.rb`)は、ユーザーからの入力文字列を`Ls`に渡してあげればよさそう。

2021-02-09 00:38 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +  def initialize(pathname, terminal_width = 120, long_format: false, reverse: false, include_dot_file: false)
`ls_oop.rb`で、
* `pathname` のデフォルト値は呼び出し側で設定している(`Ls`としては知らない)
* ターミナルの幅のデフォルト値は`Ls`が知っている
というコードになっているので、ちぐはぐな印象を受けました。

2021-02-09 00:38 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +    @pathname = pathname
`ls_oop.rb`の呼び出し側で`Pathname`のインスタンスを作ってわたしていますが、ここで`Pathname`を使うようにすれば、`ls_oop.rb`は`Pathname`を使うという知識がなくても`Ls`を利用できると思います。

2021-02-09 00:38 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +    display_files.run
`run` に「呼び出して実行する」以上の特別な意図がないのであれば、Rubyの場合は `call` でいいかな…と思います。 https://rurema.clear-code.com/3.0.0/method/Proc/i/=3d=3d=3d.html

2021-02-09 00:38 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +    files = include_dot_file ? Dir.glob(file_path, File::FNM_DOTMATCH).sort : Dir.glob(file_path).sort
三項演算でｼｭｯとまとめているのは良いですね。

ただ、dotファイルを含めるか含めないか?の処理の結果得られる`files`と思っていたら、`sort`もしていたのでちょっと身構えました(`.sort`が2箇所にあるのも気になります)。

明示的に、

```ruby
files = include_dot_file ? Dir.glob(file_path, File::FNM_DOTMATCH) : Dir.glob(file_path)
files.sort! # filesではここでしか使っていないので破壊的に並び変えても問題ない
```
としてもいいかもしれません。
`sort!`がいやだな…という場合の工夫の余地は色々ありそうです。

あるいは、L29の `reverse` の判定は要は並び変えですから、これらをまとめてもいいかもしれませんね。いずれにしても、

* 処理対象となるデータの特定(この場合はファイル群)
* 対象となるデータへの操作

は分けておいたほうが読み手への負担は減ると思います。今回でいえば:
* ファイルのリストにドットファイルを含めるかどうか
* 取得したファイルのリストを並び替えるのは昇順か逆順か

という整理のほうがよさそうに思いました。現状は:
* ファイルのリストにドットファイルを含めるかどうかの結果得たリストを昇順に並べる
* 昇順に並べているファイルを逆順にするかどうかを判定して、逆順指定なら逆順にする
という整理になっているように読めました。

2021-02-09 00:56 UTC, kakutani requested changes
バグを見つけてしまった…

2021-02-09 00:56 UTC, kakutani commented on 08.ls_object/lib/ls_short.rb
> +    row = (basenames.size / column.to_f).ceil
ターミナルの幅よりも長い名前のファイルがあるとここでエラーになりそうです。

…なりました(`ls`コマンドは折り返して表示している:

![image](https://user-images.githubusercontent.com/2160/107300489-fadb3d00-6abc-11eb-8b33-b7c598e9595e.png)

`column`がかならず1はあるようにすればいいのかな。

2021-02-13 00:37 UTC, alto-I commented on 08.ls_object/lib/ls.rb
> +require_relative './ls_long'
すいません、これはただ自分がちゃんと理解していないだけです🙇
以下のように修正しました。
~~~ruby
require_relative 'ls_long'
require_relative 'ls_short'
~~~

2021-02-13 00:37 UTC, alto-I commented on 08.ls_object/lib/ls.rb
> +require_relative './ls_short'
同上です。

2021-02-15 21:20 UTC, alto-I commented on 08.ls_object/ls_oop.rb
> +require './lib/ls'
下記のように修正しました！
~~~ruby
require 'optparse'
require_relative 'lib/ls'
~~~

2021-02-15 21:22 UTC, alto-I commented on 08.ls_object/ls_oop.rb
> +path = ARGV[0] || '.'
`ls_oop.rb`でpathのデフォルトをカレントディレクトリにするように修正しました！
~~~ruby
  def initialize(pathname: '.', terminal_width: 120, long_format: false, reverse: false, include_dot_file: false)
    @pathname = Pathname(pathname)
    @terminal_width = terminal_width
    @long_format = long_format
    @reverse = reverse
    @include_dot_file = include_dot_file
  end
~~~

2021-02-15 21:23 UTC, alto-I commented on 08.ls_object/ls_oop.rb
> +pathname = Pathname(path)
上記と被りますが`initialize`メソッドの部分で`pathname`を取得するように変更しました！
~~~ruby
@pathname = Pathname(pathname)
~~~

2021-02-15 21:26 UTC, alto-I commented on 08.ls_object/lib/ls.rb
> +  def initialize(pathname, terminal_width = 120, long_format: false, reverse: false, include_dot_file: false)
そういう視点は抜け落ちておりました🙇
どちらもデフォルト値を設定しました。
コードは上と同じものになるので省きます。

2021-02-15 21:27 UTC, alto-I commented on 08.ls_object/lib/ls.rb
> +    @pathname = pathname
被っているので省略します🙇

2021-02-15 21:30 UTC, alto-I commented on 08.ls_object/lib/ls.rb
> +    display_files.run
`LsLong`クラスと`LsShort`クラスにの`run`メソッドを`call`メソッドに変更しました！
~~~ruby
  def output
    files = files_according_to_options
    display_files = long_format ? LsLong.new(files) : LsShort.new(files, terminal_width)
    display_files.call
  end
~~~
これで合っているか自信ないので、ご指摘いただいた意図を間違って汲み取っていたら言ってください！

2021-02-15 21:32 UTC, alto-I commented on 08.ls_object/lib/ls.rb
> +    files = include_dot_file ? Dir.glob(file_path, File::FNM_DOTMATCH).sort : Dir.glob(file_path).sort
ご説明が分かりやすく大変参考になります！
以下のようにコードを修正しました。
~~~ruby
  def files_according_to_options
    file_path = pathname.join('*')
    files = include_dot_file ? Dir.glob(file_path, File::FNM_DOTMATCH) : Dir.glob(file_path)
    reverse ? files.sort.reverse : files.sort
~~~

2021-02-15 21:33 UTC, alto-I commented on 08.ls_object/lib/ls_short.rb
> +    row = (basenames.size / column.to_f).ceil
バグを見つけていただきありがとうございます😳
以下のように修正し、`column`が計算上0になる場合は1になるようにしました！
~~~ruby
  def lines
    column = @terminal_width / (max_filename_length + 1)
    column = 1 if column.zero?
    (basenames.size / column.to_f).ceil
  end
~~~

2021-02-16 01:10 UTC, kakutani reviewed
バグ修正おつかれさまです! テストコードも書いてあって良いですね。再びこまかいところをコメントしました。

2021-02-16 01:10 UTC, kakutani commented on 08.ls_object/ls_oop.rb
> +ls = if ARGV[0].nil?
好みの問題だし、RuboCopに怒られるかもですが、`if`ブロックで生じるインデントが無駄だなーと思うので、
```ruby
ls =
  if ARGV[0].nil?
    ...
  else
    ...
  end
```
としてもらえたほうが落ち着いて読めます :)

…が、ここって `pathname` が `nil` になっちゃう場合に備えたハンドリングなのですね…。

```ruby
path = ARGV[0] || '.'
puts Ls.new(pathname: path,...).output
```

でもよさそう。`Ls`を呼び出す側として何も知らないふりをしなくてもいいかなと思いました。
…と書いていて、Lsの引数の名前も`pathname`じゃなくて`path`でもいいかも。

2021-02-16 01:10 UTC, kakutani commented on 08.ls_object/test_ls_oop.rb
> +require './ls_oop'
`require_relative`

2021-02-16 03:43 UTC, alto-I commented on 08.ls_object/ls_oop.rb
> +ls = if ARGV[0].nil?
なるほど。確かにすこしくどい書き方だったのかもしれません😅
ご指摘受けた通りに修正しました！
~~~ruby
path = ARGV[0] || '.'
puts Ls.new(pathname: path, terminal_width: terminal_width, **params).output
~~~

2021-02-16 03:44 UTC, alto-I commented on 08.ls_object/test_ls_oop.rb
> +require './ls_oop'
見落としていた！
以下のように修正しました！
~~~ruby
require_relative 'ls_oop'
~~~

2021-02-16 10:48 UTC, kakutani reviewed
LsShortを読みました。LsLongのほうでも参考になるかもしれません(ならないかもしれません)

2021-02-16 10:48 UTC, kakutani commented on 08.ls_object/lib/ls_short.rb
> +    files_format(basenames, lines)
ここは`files_format` という名詞よりは `format_files`という動詞のほうが適切かな…と思ったのですが、`basenames`も`lines`もprivateメソッドから取得できるので、引数で渡さなくてもよさそうですね…。

となると、現行の `files_format`のメソッド本体を`call`にインライン化して、整理しなおすほうが意図は伝わりやすくなるかもしれません。

2021-02-16 10:48 UTC, kakutani commented on 08.ls_object/lib/ls_short.rb
> +    (basenames.size / column.to_f).ceil
行数とは、表示したいファイルの数を、表示カラム数で割ったものを切り上げたものである、といううこと示すなら:

```ruby
def lines
  (basenames.size / colunm_size).ceil
end

private
def column_size
   cols = @terminal_width / (max_filename_length + 1)
   (basenames.size / (cols.zero? 1 : cols).ceil  
end
```

ともできますね。このままでも読みづらい、というわけではありませんが、意図を明確にするという意味ではこうも整理できますね、という例です。

2021-02-16 10:48 UTC, kakutani commented on 08.ls_object/lib/ls_short.rb
> +    @files.map { |file| File.basename(file) }
大した計算量ではないので、敏感にならなくてもよかもしれませんが、呼び出されるたびに`map`の処理が走りますね。

実は`LsShort`として必要なのは、`@files`ではなくて`basenames`のほうのようなので、`initialize`のときに `@basenames = files.map...` としておいて、`@basenames`を使うほうが良いのかも。

2021-02-16 10:48 UTC, kakutani commented on 08.ls_object/lib/ls_short.rb
> +    basenames.max_by(&:length).size
呼び出されるたびに処理が走りますが、このオブジェクトでは1回計算しておいて、あとは計算済の結果を返せば十分かも。

```
@_max_filename_length ||= basenames.max_by(&:length).size
```

`size`と`length`が混じってますが違いはなさそう…

2021-02-16 10:48 UTC, kakutani commented on 08.ls_object/lib/ls_short.rb
> +    end.join("\n")
これがダメというわけではありませんが、`do...end` は字面としては手続きを書く(返す値は特に使わない)のがしっくりくるので、式として使う(返す値を使う)なら、
`display_files.map { |f| format_files(f) }.join("\n")` のほうがしっくりきます。

2021-02-16 10:48 UTC, kakutani commented on 08.ls_object/lib/ls_short.rb
> +    end.join.rstrip
ここも、 `files.map { |f| ...}.join.rstrip` でよさそう。

2021-02-17 04:15 UTC, kakutani reviewed
`ls_long.rb`を読みました。

2021-02-17 04:15 UTC, kakutani commented on 08.ls_object/lib/ls_long.rb
> +  attr_reader :file
`attr_reader`は他のオブジェクトから読み出せるようにするメソッドで、`file`は公開していないので見せる必要は無さそうです。

2021-02-17 04:15 UTC, kakutani commented on 08.ls_object/lib/ls_long.rb
> +    files_detail = @files.each.map do |file|
`each`は不要です。`map`しているので、`do..end`よりも`{..}`がよさそうです。
変数名、`file_details`のほうが良いかもしれません。

2021-02-17 04:15 UTC, kakutani commented on 08.ls_object/lib/ls_long.rb
> +    end
```suggestion
    keys.map { |key| files.map { |file| file[key].size } }.max
```

2021-02-17 04:15 UTC, kakutani commented on 08.ls_object/lib/ls_long.rb
> +    max_lengths = find_max_text(files_detail)
左辺が物語っていますが、名前は `find_max_text`(最大のテキストを探す)よりも、`max_lengths(files_detail)` でよさそうです。

2021-02-17 04:15 UTC, kakutani commented on 08.ls_object/lib/ls_long.rb
> +    end.sum
```suggestion
    total = files_detail.sum { |file| file[:block] }
```

2021-02-17 04:15 UTC, kakutani commented on 08.ls_object/lib/ls_long.rb
> +    end
```suggestion
    body = files_detail.map { |f| formatted_for_display(f, *max_lengths) }
```

2021-02-17 04:15 UTC, kakutani commented on 08.ls_object/lib/ls_long.rb
> +  end
```suggestion
    numbers.map { |n| permission(:"#{n}") }.join
```

2021-02-17 04:15 UTC, kakutani commented on 08.ls_object/lib/ls_long.rb
> +    }[num]
`permission`を呼び出すたびにハッシュオブジェクトが生成されるけれど中身は変わらないので、定数にするかメモ化するなどしておくと良さそうです。

2021-02-17 04:15 UTC, kakutani commented on 08.ls_object/lib/ls_long.rb
> +    timestamps = File.lstat(file).mtime
`timestamps`と複数形なのはなぜでしょう?

2021-02-17 04:15 UTC, kakutani commented on 08.ls_object/lib/ls_long.rb
> +      (file[:linked_file]).to_s
```suggestion
      file[:linked_file]
```

`#linked_file(file)`の戻り値を必ずStringにしておけばよさそうです。

2021-02-17 04:15 UTC, kakutani commented on 08.ls_object/lib/ls_long.rb
> +    " -> #{File.readlink(file)}" if filetypes(file) == 'l'
`#formatted_for_display`のところでもコメントしましたが、ここでは`nil`を返さないようにするのがよさそうです(空文字列を返す)。

あと、`filetypes(file) == 'l'`と、リテラルが漏れているのが勿体ないなと思いました。
`if symlink?(file)` みたいな感じで判定できたほうがスマートかなと思いました。

2021-03-07 10:39 UTC, alto-I commented on 08.ls_object/lib/ls_short.rb
> +    files_format(basenames, lines)
確かに`call`があまり意味のないメソッドになってしまっていました。`files_format`のメソッドを`call`に持ってくるように修正しました！
~~~ruby
  def call
    files_matrix = @basenames.each_slice(lines).map { |file| file }
    (lines - files_matrix.last.size).times do
      files_matrix.last.push ''
    end
    display_files = files_matrix.transpose
    display_files.map { |f| format_lines(f) }.join(("\n"))
  end
~~~

2021-03-07 10:41 UTC, alto-I commented on 08.ls_object/lib/ls_short.rb
> +    (basenames.size / column.to_f).ceil
`columns`とメソッド名を修正して、`to_f`メソッドは`columns`内で行うようにしました！
~~~ruby
  def columns
    cols = @terminal_width / (max_filename_length + 1)
    cols.zero? ? 1.0 : cols.to_f
  end
~~~

2021-03-07 10:43 UTC, alto-I commented on 08.ls_object/lib/ls_short.rb
> +    @files.map { |file| File.basename(file) }
試しに`p`メソッドで呼び出したところ8回も`map`処理が走っていました😅
ご指摘のとおり`initialize`で`basename`を呼び出すようにしました！
~~~ruby
  def initialize(files, terminal_width)
    @basenames = files.map { |file| File.basename(file) }
    @terminal_width = terminal_width
  end
~~~

2021-03-07 10:45 UTC, alto-I commented on 08.ls_object/lib/ls_short.rb
> +    basenames.max_by(&:length).size
確かにその方が無駄がないですね😳 もっとそのような視点を持ってコードを書けるようになりたいです！
下記のように修正しました！
~~~ruby
  def max_filename_length
    @max_filename_length ||= @basenames.max_by(&:length).size
  end
~~~

2021-03-07 10:46 UTC, alto-I commented on 08.ls_object/lib/ls_short.rb
> +    end.join("\n")
そこの使い分けを意識できてなかったです😅 ご指摘のとおり修正しました！
~~~ruby
display_files.map { |f| format_lines(f) }.join(("\n"))
~~~

2021-03-07 10:47 UTC, alto-I commented on 08.ls_object/lib/ls_short.rb
> +    end.join.rstrip
下記のように修正しました！
~~~ruby
files.map { |f| f.ljust(max_filename_length + 1) }.join.rstrip
~~~

2021-03-07 10:47 UTC, alto-I commented on 08.ls_object/lib/ls_long.rb
> +  attr_reader :file
ほんとですね😅 削除しました！(ls_short.rbも同様）

2021-03-07 10:48 UTC, alto-I commented on 08.ls_object/lib/ls_long.rb
> +    files_detail = @files.each.map do |file|
下記の通りに修正しました！
~~~ruby
file_details = @files.map { |f| build_file_data(f) }
~~~

2021-03-07 10:48 UTC, alto-I commented on 08.ls_object/lib/ls_long.rb
> +    end
下記の通りに修正しました！
~~~ruby
keys.map { |key| files.map { |f| f[key].size }.max }
~~~

2021-03-07 10:50 UTC, alto-I commented on 08.ls_object/lib/ls_long.rb
> +    max_lengths = find_max_text(files_detail)
メソッド名を`max_lengths`に修正しました！
~~~ruby
  def max_lengths(files)
    keys = %i[links user group size]
    keys.map { |key| files.map { |f| f[key].size }.max }
  end
~~~

2021-03-07 10:53 UTC, alto-I commented on 08.ls_object/lib/ls_long.rb
> +    end.sum
ご指摘のとおり修正しました！
~~~ruby
total = file_details.sum { |file| file[:block].to_i }
~~~

2021-03-07 10:54 UTC, alto-I commented on 08.ls_object/lib/ls_long.rb
> +    end
ご指摘のとおり修正しました！
~~~ruby
body = file_details.map { |file| formatted_for_display(file, *max_lengths) }
~~~

2021-03-07 10:54 UTC, alto-I commented on 08.ls_object/lib/ls_long.rb
> +  end
ご指摘のとおり修正しました！
~~~ruby
numbers.map { |n| PERMISSION[n.to_i] }.join
~~~

2021-03-07 10:56 UTC, alto-I commented on 08.ls_object/lib/ls_long.rb
> +    }[num]
定数にしました！
~~~ruby
PERMISSION = ['---', '--x', '-w-', '-wx', 'r--', 'r-x', 'rw-', 'rwx'].freeze
~~~

2021-03-07 10:56 UTC, alto-I commented on 08.ls_object/lib/ls_long.rb
> +    timestamps = File.lstat(file).mtime
すいません特に意味はないので`timestamp`に修正しました😅

2021-03-07 10:59 UTC, alto-I commented on 08.ls_object/lib/ls_long.rb
> +      (file[:linked_file]).to_s
どの場合でもStringを返すようにしたので削除しました！`linked_file`メソッドについては次のコメントで修正内容記載しています！

2021-03-07 10:59 UTC, alto-I commented on 08.ls_object/lib/ls_long.rb
> +    " -> #{File.readlink(file)}" if filetypes(file) == 'l'
下記のように修正しました！
~~~ruby
  def linked_file(file)
    FileTest.symlink?(file) ? " -> #{File.readlink(file)}" : ''
  end
~~~

2021-04-01 14:24 UTC, komagata requested changes

2021-04-01 14:24 UTC, komagata commented on 08.ls_object/lib/ls_long.rb
> +class LsLong
LsLongと二語になるのであれば、

`Ls::Long`, `Ls::Short`のように全てのクラスを`Ls`のネームスペースに入れてしまった方が良いかもです

2021-04-02 11:43 UTC, alto-I commented on 08.ls_object/lib/ls.rb
> +  class Ls::Long
LongクラスのLsクラスのネームスペースに入れました！

2021-04-02 11:43 UTC, alto-I commented on 08.ls_object/lib/ls.rb
> +  class Ls::Short
ShortクラスのLsクラスのネームスペースに入れました！

2021-04-02 12:54 UTC, komagata requested changes

2021-04-02 12:54 UTC, komagata commented on 08.ls_object/lib/ls.rb
> +  class Ls::Long
クラス内クラスというのは使わなくはないのですが、一般的ではないので特に理由がなければ基本的にはLsモジュールをネームスペースとして使うようにした方が良さそうです〜

2021-04-02 23:03 UTC, alto-I commented on 08.ls_object/lib/ls.rb
> +class Ls::Long
LongクラスをLsクラスの外に記述しました！

2021-04-02 23:04 UTC, alto-I commented on 08.ls_object/lib/ls.rb
> +class Ls::Short
ShortクラスをLsクラスの外に記述しました！

2021-04-03 02:33 UTC, komagata requested changes

2021-04-03 02:33 UTC, komagata commented on 08.ls_object/lib/ls.rb
> +class Ls::Long
オブジェクト指向プログラミングのカリキュラムの参考のgemのあたりをみると参考になるかもですが、（どのような名前構成、ネームスペースになっているかいくつかのgemのソースをみてみてください〜）基本的に一つのライブラリには共通のネームスペースをmoduleで一つ用意して全てのクラスをその下に入れます。

https://bootcamp.fjord.jp/practices/211

例えばこういう感じです。

```ruby
module Ls
  class Command
  end

  class Long
  end

  ...
end
```

2021-04-03 10:58 UTC, alto-I commented on 08.ls_object/lib/ls.rb
> +module Ls
細かく教えていただきありがとうございます！すいませんもっとよく調べておくべきでした、反省します🙇
Lsモジュールを名前空間として修正しました！

2021-04-05 05:06 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-02-08 08:01 UTC, merged